#!groovy

stage('Initial'){
node{
echo 'Initial stage'
dir('/home/rainman/Downloads'){

    stash includes: '*.torrent,pipe.sh', name: 'stash_stuff'
    }
    }
}


stage('Build') {
   parallel linux: {
        node('python') {
        echo 'Building in python node(aka localhost)'
	sh '/home/rainman/Downloads/pipe.sh'
	
    }
 },
    linux2: {
       node('pi') {
        echo 'Building in raspberry node'
	dir('/home/pi'){
	unstash 'stash_stuff'
	}
	sh '/home/pi/pipe.sh'
    }
 },
    
    linux3: {
        node('pi') {
        echo 'Deploying....'
	writeFile file:'/home/pi/test_home',text:'Deployed'
	dir('/home/pi'){
        echo 'Unstashing'
	unstash 'stash_stuff'
        echo 'Sleeping'
        sleep(60)
	}
    }
  }
,linux4:{

   node('pi'){
       echo '4th executor process for pi?'
       writeFile file:'/home/pi/test_4th',text:'4th executor'
     }
  }
}
